frontend_review_form:
    pattern: /create_reviews
    defaults: { _controller: FrontendContentBundle:Review:CreateReview }
    
frontend_reviews:
    pattern: /reviews
    defaults: { _controller: FrontendContentBundle:Review:ListReview }
    
frontend_reviews2:
    pattern: /company/reviews
    defaults: { _controller: FrontendContentBundle:Review:ListReview }
    
request_callback:
    pattern:  /request_callback
    defaults: { _controller: FrontendContentBundle:Callback:requestCallback }
  
NNWelcome_frontend_site_map:
    pattern:  /site_map
    defaults: { _controller: FrontendContentBundle:Menu:siteMap }

frontend_search_content:
    pattern:  /content/search
    defaults: { _controller: FrontendContentBundle:Content:seacheResult }
  
frontend_search_catalog:
    pattern:  /catalog/search/{page}
    defaults: { _controller: FrontendContentBundle:Catalog:seacheResult, page: 1 }

NNWelcome_frontend_catalog:
    pattern:  /catalog/{alias}
    defaults: { _controller: FrontendContentBundle:Catalog:index, alias: 'catalog' }
    
NNWelcome_frontend_catalog_show:
    pattern:  /catalog/{category}/{alias}
    defaults: { _controller: FrontendContentBundle:Catalog:show }

NNWelcome_frontend_news_list_categories:
    pattern:  /news
    defaults: { _controller: FrontendContentBundle:News:ShowListCategories }

NNWelcome_frontend_news_category:
    pattern:  /news/{category}
    defaults: { _controller: FrontendContentBundle:News:ShowCategory }
    
NNWelcome_frontend_news_item:
    pattern:  /news/{category}/{alias}
    defaults: { _controller: FrontendContentBundle:News:ShowNews }

NNWelcome_frontend_projects:
    pattern:  /projects
    defaults: { _controller: FrontendContentBundle:Project:ShowListProjects }

NNWelcome_frontend_projects_reset_filter:
    pattern:  /projects/year/reset
    defaults: { _controller: FrontendContentBundle:Project:ResetFilterProject }
    
NNWelcome_frontend_projects_filter:
    pattern:  /projects/year/{year}
    defaults: { _controller: FrontendContentBundle:Project:FilterProject }
    
NNWelcome_frontend_projects_item:
    pattern:  /projects/{alias}
    defaults: { _controller: FrontendContentBundle:Project:ShowProject }

frontend_content_tree1:
    pattern:  /{category}/{alias}
    defaults: { _controller: FrontendContentBundle:Content:show }
    
frontend_content_tree2:
    pattern:  /{category1}/{category2}/{alias}
    defaults: { _controller: FrontendContentBundle:Content:show }
    
frontend_content_tree3:
    pattern:  /{category1}/{category2}/{category3}/{alias}
    defaults: { _controller: FrontendContentBundle:Content:show }
    
frontend_content_tree4:
    pattern:  /{category1}/{category2}/{category3}/{category4}/{alias}
    defaults: { _controller: FrontendContentBundle:Content:show }

frontend_content_tree5:
    pattern:  /{category1}/{category2}/{category3}/{category4}/{category5}/{alias}
    defaults: { _controller: FrontendContentBundle:Content:show }
    
frontend_content:
    pattern:  /{alias}
    defaults: { _controller: FrontendContentBundle:Content:show }
    
homepage:
    pattern:   /
    defaults:  { _controller: FrontendContentBundle:Content:show, alias: "homepage" }