parameters:
#    nn_welcome_location.example.class: NNWelcome\LocationBundle\Example

services:
#    nn_welcome_location.example:
#        class: %nn_welcome_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
