NNWelcome_location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /admin

NNWelcome_layout:
    resource: "@LayoutBundle/Resources/config/routing.yml"
    prefix:   /admin
    
NNWelcome_callback:
    resource: "@CallbackBundle/Resources/config/routing.yml"
    prefix:   /admin

NNWelcome_project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /admin

NNWelcome_news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /admin

_imagine:
    resource: .
    type:     imagine
    
NNWelcome_image_gallery:
    resource: "@ImageGalleryBundle/Resources/config/routing.yml"
    prefix:   /admin

NNWelcome_file_category:
    resource: "@FileCategoryBundle/Controller/"
    type:     annotation
    prefix:   /admin 
  
NNWelcome_catalog:
    resource: "@CatalogBundle/Resources/config/routing.yml"
    prefix:   /admin
 
NNWelcome_menu:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /admin
    
NNWelcome_web_item:
    resource: "@WebItemBundle/Resources/config/routing.yml"
    prefix:   /admin

NNWelcome_content:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /admin

NNWelcome_login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    prefix:   /
    
NNWelcome_frontend:
    resource: "@FrontendContentBundle/Resources/config/routing.yml"
    prefix:   /
    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
